theme: jekyll-theme-minimal
title: Battesimo di Marco
description: 14 Ottobre 2023 ore 11 Chiesa di San Raimondo Nonnato, Roma ([qui](https://maps.app.goo.gl/w43DzhpSeExghGmx5))
logo: /assets/img/invito_battesimo2.jpg
